package-lock.json
package.json
src/app/components/InverterCharger.js
src/app/components/SelectorButton/SelectorButton.scss
src/app/components/SelectorButton/index.js
src/app/components/ShoreInputLimit/index.js
src/app/components/ShoreInputLimitSelector/ShoreInputLimitSelector.js
src/app/components/ShoreInputLimitSelector/ShoreInputLimitSelector.scss
src/app/components/ShoreInputLimitSelector/index.js
src/css/styles.scss

* Create new component for selector buttons
* Move css code for each component in its own folder

Refactor Shore input limit css code

---

scripts/fake-broker.js
src/app/components/Metrics.js
src/app/components/Solar/index.js

Feature disabled pending new design

Add solar panels

---

src/app/components/ActiveSource/ActiveSource.js

Hide active input source its AC_SOURCE_TYPE is set to
NOT_IN_USE.

Hide active input source if it is not used

---

src/app/components/InverterCharger/InputLimit.js

Remove the warning text that is shown when the shore power is not
configured in the system.

Remove warning text

---

src/app/components/MetricValues/MetricValues.scss

Fix flex abbreviation causing rendering issues for (battery) metrics

---

src/app/components/Header/Header.scss

Align header elements with the metrics columns

---

src/app/components/Header/Header.js

Replace showRemoteConsole placeholder topic

---

src/app/components/App.js
src/app/components/Header/Header.js
src/app/components/Header/Header.scss
src/app/components/Views/Metrics.js
src/css/styles.scss
src/css/variables.scss

Large resolution scaling

---

src/app/components/App.js
src/app/components/Header/Header.js
src/app/components/Views/MqttUnavailable.js

Add remote console button without MQTT

---

cypress/integration/pagination.spec.js
cypress/integration/rendering.spec.js
cypress/support/commands.js
src/app/components/App.js
src/app/components/Battery/Battery.scss
src/app/components/Header/Header.js
src/app/components/Header/Header.scss
src/app/components/Header/Header.test.js
src/app/components/HidingContainer.js
src/app/components/Views/Metrics.js
src/css/styles.scss
src/css/variables.scss

WIP: Screens pagination

---

src/app/components/ActiveSource/ActiveSource.js
src/app/components/Generators/GeneratorFp.js
src/app/components/Generators/GeneratorRelay.js
src/app/components/Generators/Generators.js
src/app/mqtt/MqttSubscriptions.js

Add combined generator control and metrics component

---

src/app/components/Views/RemoteConsole/RemoteConsole.js

Fix keyboard control for the Remote Console

---

src/app/components/InverterCharger/InputLimitSelector.js

Add 3A to input limit selector

---

cypress/integration/rendering.spec.js
src/app/components/Header/Header.scss
src/css/styles.scss
src/css/texts.scss

Improve scaling on large screen

---

src/app/Marine2/components/ui/RadioButton/RadioButton.tsx
src/app/Marine2/components/ui/ToggleSwitch/ToggleSwitch.tsx

Fix alignment issues for buttons on different display splits

---

src/app/Marine2/components/boxes/BatteriesOverview/BatteriesOverview.tsx
src/app/Marine2/components/boxes/Battery/Battery.tsx
src/app/Marine2/components/boxes/EnergyOverview/EnergyOverview.tsx
src/app/Marine2/components/boxes/Tanks/Tank.tsx
src/app/Marine2/components/boxes/Tanks/Tanks.tsx
src/app/Marine2/components/ui/ProgressBar/ProgressBar.tsx
src/app/Marine2/components/ui/SettingsMenu/SettingsMenu.tsx

- Changed the Pagination flow for the batteries overview to match the design 
- Clean up tanks component and truncate tank name on compact mode
- Changed progress bar width (or height) to match the design file
- Fixed broken settings menu modal on small screens 
- Added pagination to Energy Overview compact component

Small fixes and clean up components

---

src/app/Marine2/components/boxes/Tanks/Tank.tsx
src/app/Marine2/components/boxes/Tanks/Tanks.tsx
src/app/Marine2/components/ui/ProgressBar/ProgressBar.tsx

- Changed the progress bar to the new design
- Hide the progress bar if the box size is less than 400px
- Add fixed size for progress bars

Tanks small fixes

---

src/app/Marine2/components/boxes/Tanks/Tank.tsx

Bug Fix: Tank bar offset on empty tanks

---

package-lock.json
src/app/Marine2/components/boxes/EnvironmentOverview/EnvironmentOverview.tsx
src/app/Marine2/components/boxes/Tanks/Tank.tsx

Fix empty system overview components

---

src/app/Marine2/components/boxes/Tanks/Tank.tsx

Reverts victronenergy/venus-html5-app#306

Revert "Add support for all tank measurement units"

---

src/app/Marine2/components/boxes/Tanks/Tank.tsx
src/app/Marine2/components/boxes/Tanks/Tanks.tsx

- Show all tanks in tank details overview
- Show tanks with missing remaining and total capacity

Show all tanks in details overview

---

TOPICS.md

Fixed spelling errors in TOPICS.md.

Fixed spelling errors in TOPICS.md

---

src/app/Marine2/components/boxes/EnvironmentOverview/EnvironmentOverview.tsx
src/app/Marine2/components/boxes/EnvironmentOverview/HumidityData.tsx
src/app/Marine2/components/boxes/EnvironmentOverview/PressureData.tsx
src/app/Marine2/components/boxes/EnvironmentOverview/TemperatureData.tsx

Adjusted sensor visibility logic to also show temperature sensors:

Adjusted sensor visibility logic.

---

package-lock.json
package.json
src/app/Marine2/components/boxes/BatteriesOverview/BatteriesOverview.tsx
src/app/Marine2/components/boxes/Battery/Battery.tsx
src/app/Marine2/components/boxes/EnvironmentOverview/TemperatureData.tsx
src/app/Marine2/types/data/unit.ts
src/app/Marine2/utils/formatters/temperature/celcius-to-fahrenheit.ts
src/app/Marine2/utils/formatters/temperature/temperature-value-for.ts

Implemented fahrenheit support for temperatures.

Fahrenheit support

---

package-lock.json
package.json
src/app/KVNRV/components/Tanks/SmallTank.tsx
src/app/Marine2/components/boxes/Tanks/Tanks.tsx
src/app/Marine2/utils/helpers/devices/tanks/sort-tanks.ts

Closes #https://github.com/victronenergy/venus-html5-app/issues/400

feat(tanks): Sort tanks by type

---

src/app/Marine2/components/boxes/BatteriesOverview/BatteriesOverview.tsx
src/app/Marine2/components/boxes/EnergyAC/EnergyAC.tsx
src/app/Marine2/components/boxes/EnergyAlternator/EnergyAlternator.tsx
src/app/Marine2/components/boxes/EnergyDC/EnergyDC.tsx
src/app/Marine2/components/boxes/EnergyShore/EnergyShore.tsx
src/app/Marine2/components/boxes/EnergySolar/EnergySolar.tsx
src/app/Marine2/components/boxes/EnergyWind/EnergyWind.tsx
src/app/Marine2/components/boxes/GeneratorFp/GeneratorFp.tsx
src/app/Marine2/components/boxes/GeneratorRelay/GeneratorRelay.tsx
src/app/Marine2/components/ui/BatterySummary/BatterySummary.tsx
src/app/Marine2/components/ui/BatterySummary/BatteryValues/BatteryValues.tsx
src/app/Marine2/components/ui/RemoteConsole/RemoteConsole.tsx
src/app/Marine2/utils/formatters/phase/phase-unit-for.ts
src/app/Marine2/utils/formatters/phase/phase-value-for.ts

Closes https://github.com/victronenergy/venus-html5-app/issues/336

feat: display Watts or Amps based on GUI-v2 setting
